# Colab으로 실행하기

Mac에서 mecab 실행 복잡

# Word2Vec

In [ ]:
import gensim
gensim.__version__

# Gensim은 파이썬 기반의 오픈 소스 자연어 처리(NLP) 라이브러리로,
# 특히 주제 모델링(Topic Modeling), 문서 유사도 계산, 벡터 공간 모델(VSM) 등에 특화되어 있습니다.
# 대용량의 텍스트 데이터를 효율적으로 처리하고, 통계적인 기법을 활용하여 텍스트 마이닝 작업을 수행할 수 있도록 설계되었습니다.

# NLTK와의 비교

    # NLTK:

        # 주로 텍스트 전처리, 토큰화, 품사 태깅, 구문 분석 등 기초적인 NLP 작업에 초점을 맞추고 있습니다.
        # 교육용으로도 많이 사용되며, 다양한 코퍼스와 학습 자료를 제공합니다.
        # 상대적으로 소규모 데이터 처리에 적합합니다.

    # Gensim:

        # 주제 모델링, 단어 임베딩, 유사도 계산 등 벡터 공간 모델과 통계적 기법에 특화되어 있습니다.
        # 대용량 데이터 처리를 효율적으로 지원합니다.
        # 실제 산업 현장에서 주제 분석이나 추천 시스템 등에 활용됩니다.

'4.3.3'

In [ ]:
!pip install nltk==3.8.1

Requirement already satisfied: nltk==3.8.1 in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (4.66.5)

**NLTK (Natural Language Toolkit)**는 파이썬 기반의 자연어 처리(NLP) 라이브러리로, 자연어 텍스트를 분석하고 처리하는 데 필요한 다양한 도구와 리소스를 제공합니다.

NLTK는 텍스트 전처리, 토큰화, 품사 태깅, 문법 분석, 감정 분석, 텍스트 분류 등 다양한 자연어 처리 작업을 쉽게 수행할 수 있도록 도와줍니다.

**NLTK의 주요 기능**

> 1. 토큰화(Tokenization):

문장이나 단어 단위로 텍스트를 분리하는 과정입니다. NLTK는 텍스트를 문장 단위나 단어 단위로 나누는 데 도움을 주는 도구를 제공합니다.

예시: word_tokenize()는 문장을 단어 단위로 나눕니다.

> 2. 형태소 분석(스테밍, 레마타이제이션):

스테밍(Stemming): 단어의 어간을 추출하는 과정입니다. 예를 들어, "running", "runner", "ran"은 모두 "run"으로 변환될 수 있습니다.

레마타이제이션(Lemmatization): 단어를 사전형으로 변환하는 과정입니다. 문맥에 맞는 올바른 형태로 변환하려는 시도가 이루어집니다. 예를 들어, "better"는 "good"으로 변환됩니다.

> 3. 품사 태깅(POS tagging):

각 단어에 대해 품사(명사, 동사, 형용사 등)를 태깅해주는 기능입니다. NLTK는 이미 훈련된 품사 태깅 모델을 제공해 단어에 적절한 품사를 자동으로 태깅할 수 있습니다.

예시: nltk.pos_tag()는 단어에 품사를 태깅해줍니다.

> 4. 파싱(Parsing):

문장의 구문 구조를 분석하는 과정입니다. NLTK는 문법을 정의하고 구문 트리를 생성할 수 있는 도구를 제공합니다.

> 5. 말뭉치(Corpus) 및 워드넷(WordNet):

NLTK는 여러 코퍼스(말뭉치)와 **워드넷(WordNet)**을 내장하고 있어, 다양한 형태의 텍스트 데이터를 다룰 수 있습니다.

WordNet: 단어들의 의미와 관계(동의어, 반의어 등)를 분석할 수 있는 데이터베이스입니다.

> 6. 정규 표현식(Regular Expression):

정규 표현식을 사용해 텍스트에서 특정 패턴을 찾거나 변경할 수 있는 기능을 지원합니다.

> 7. 텍스트 분류(Text Classification):

NLTK는 텍스트 데이터를 기반으로 한 분류 작업(감정 분석, 주제 분류 등)을 위한 다양한 기계 학습 알고리즘을 제공합니다. 예를 들어, 나이브 베이즈 분류기(Naive Bayes Classifier) 등 여러 가지 분류기를 활용할 수 있습니다.

# 영어 데이터 다운로드 및 전처리

In [ ]:
import re
from lxml import etree
import urllib.request
import zipfile
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/GaoleMeng/RNN-and-FFNN-textClassification/master/ted_en-20160408.xml", filename="ted_en-20160408.xml")

('ted_en-20160408.xml', <http.client.HTTPMessage at 0x788eeab4dff0>)

In [ ]:
targetXML = open('ted_en-20160408.xml', 'r', encoding='UTF8')
target_text = etree.parse(targetXML)

# xml 파일로부터 <content>와 </content> 사이의 내용만 가져온다.
parse_text = '\n'.join(target_text.xpath('//content/text()'))

# 정규 표현식의 sub 모듈을 통해 content 중간에 등장하는 (Audio), (Laughter) 등의 배경음 부분을 제거.
# 해당 코드는 괄호로 구성된 내용을 제거.
content_text = re.sub(r'\([^)]*\)', '', parse_text)

## 데이터 살펴보기

In [ ]:
content_text[:100]

"Here are two reasons companies fail: they only do more of the same, or they only do what's new.\nTo m"

In [ ]:
# 입력 코퍼스에 대해서 NLTK를 이용해 문장 토큰화 수행
sent_text = sent_tokenize(content_text)

In [ ]:
sent_text[:3]

["Here are two reasons companies fail: they only do more of the same, or they only do what's new.",
 'To me the real, real solution to quality growth is figuring out the balance between two activities: exploration and exploitation.',
 'Both are necessary, but it can be too much of a good thing.']

In [ ]:
# 각 문장에 대해서 구두점을 제거하고, 대문자를 소문자로 변환.
normalized_text = []
for string in sent_text:
     tokens = re.sub(r"[^a-z0-9]+", " ", string.lower())
     normalized_text.append(tokens)

# 각 문장에 대해서 NLTK를 이용하여 단어 토큰화를 수행.
result = [word_tokenize(sentence) for sentence in normalized_text]

In [ ]:
print(result[:3])

[['here', 'are', 'two', 'reasons', 'companies', 'fail', 'they', 'only', 'do', 'more', 'of', 'the', 'same', 'or', 'they', 'only', 'do', 'what', 's', 'new'], ['to', 'me', 'the', 'real', 'real', 'solution', 'to', 'quality', 'growth', 'is', 'figuring', 'out', 'the', 'balance', 'between', 'two', 'activities', 'exploration', 'and', 'exploitation'], ['both', 'are', 'necessary', 'but', 'it', 'can', 'be', 'too', 'much', 'of', 'a', 'good', 'thing']]

## 영어 word2vec 훈련

In [ ]:
from gensim.models import Word2Vec

# **코퍼스(Corpus)**는 자연어 처리(NLP)에서 분석이나 학습을 위해 수집된 대량의 텍스트 데이터를 말합니다.
# 코퍼스는 단순히 텍스트의 모음이 아니라, 특정 작업을 위해 준비된 자료로, 다양한 형태의 언어 데이터(문장, 문서 등)가 포함되어 있습니다.
# 코퍼스는 언어 모델을 학습하거나 특정 언어적 현상을 분석할 때 사용됩니다.

model = Word2Vec(
    sentences=result, # 코퍼스
    vector_size=100, # 각 단어의 임베딩된 차원 즉 단어의 벡터 크기
    window=5, # Context Window의 크기
    min_count=5, # 단어 최소 빈도수 제한. 즉 빈도가 낮은 단어는 학습 안함
    workers=4, # 학습을 위한 프로세서(cpu)의 개수
    sg=1 # Skip Gram 사용 여부. 0이면 CBOW, 1이면 Skip Gram
)

In [ ]:
# 단어에 대한 유사도 구하기. most_similar : 코사인 유사도
model.wv.most_similar("man")

[('woman', 0.7863466143608093),
 ('guy', 0.752658486366272),
 ('boy', 0.7222238183021545),
 ('soldier', 0.7025302052497864),
 ('rabbi', 0.686120867729187),
 ('pope', 0.6858847141265869),
 ('gentleman', 0.6778992414474487),
 ('son', 0.6774143576622009),
 ('policeman', 0.6720773577690125),
 ('adage', 0.6684863567352295)]

In [ ]:
model.wv.most_similar("woman")

[('girl', 0.7905932068824768),
 ('man', 0.7863466143608093),
 ('lady', 0.7216938734054565),
 ('soldier', 0.7127863764762878),
 ('boy', 0.7097004055976868),
 ('child', 0.7059670686721802),
 ('husband', 0.6854088306427002),
 ('victim', 0.6818000674247742),
 ('daughter', 0.6789309978485107),
 ('mary', 0.6736324429512024)]

In [ ]:
# 모델이 학습한 벡터를 홝인
model.wv["man"] # wv(word vector)는 딕셔너리

array([-0.25209996,  0.0592721 , -0.02361586, -0.16687812,  0.03744238,
       -0.25811782,  0.16594514,  0.3461516 ,  0.02332711, -0.13996726,
       -0.36392605, -0.26178896,  0.131253  ,  0.3351751 , -0.32093954,
       -0.14890963,  0.33874196, -0.10975154, -0.02637271, -0.39316288,
        0.36327323,  0.4009066 ,  0.19405651, -0.18090706,  0.10744906,
       -0.33540955,  0.13118781, -0.2660451 , -0.14262499, -0.31511462,
       -0.27587935,  0.24813367,  0.28674805, -0.01199152,  0.11911368,
        0.0592097 , -0.18762289,  0.06262171, -0.36426148, -0.24696389,
       -0.1003834 , -0.6593307 , -0.19362263, -0.05529572,  0.0343897 ,
       -0.23777136, -0.29639354, -0.01753124,  0.16734141, -0.01686015,
        0.3761276 , -0.36791182,  0.18752538,  0.335562  ,  0.14224863,
       -0.04480827, -0.21389872, -0.07913215, -0.7388753 , -0.3574352 ,
       -0.1578209 , -0.19215086,  0.10584897,  0.23631507, -0.35433114,
        0.20044625, -0.34364194, -0.04273351, -0.55432653,  0.28665653,
        0.10842924,  0.09311153,  0.8043948 ,  0.07006372,  0.3727422 ,
       -0.0335276 ,  0.1416691 , -0.03604173, -0.5606963 ,  0.39604613,
       -0.18078929, -0.05088511, -0.41795388,  0.17546596, -0.13694225,
       -0.338684  ,  0.24420065,  0.30153352, -0.3913652 , -0.47088167,
        0.07010242,  0.02224962,  0.00359321,  0.20886569,  0.5062727 ,
        0.18755773,  0.3821491 , -0.42702448, -0.4034594 ,  0.03289991],
      dtype=float32)

In [ ]:
len(model.wv["man"])

100

In [ ]:
# 저장
from gensim.models import KeyedVectors
model.wv.save_word2vec_format("eng_w2v") # 모델 저장

loaded_model = KeyedVectors.load_word2vec_format("eng_w2v") # 모델 로딩

# 한국어 데이터 다운로드 및 전처리

In [ ]:
# !pip install konlpy
# !pip install mecab-python
# !bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.4)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (24.1)
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 67.6 MB/s eta 0:00:00
Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 28.6 MB/s eta 0:00:00
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.5.0 konlpy-0.6.0
Collecting mecab-python
  Downloading mecab-python-1.0.0.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... done
Collecting mecab-python3 (from mecab-python)
  Downloading mecab_python3-1.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.1 kB)
Downloading mecab_python3-1.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (581 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.7/581.7 kB 8.0 MB/s eta 0:00:00
Building wheels for collected packages: mecab-python
  Building wheel for mecab-python (setup.py) ... done
  Created wheel for mecab-python: filename=mecab_python-1.0.0-py3-none-any.whl size=1230 sha256=6c1074babf057de12020d7aa17789aa558e0a66583191c66729b9ef4f25f030a
  Stored in directory: /root/.cache/pip/wheels/ec/41/c8/ce8fb469be2547ce596c4000613806505dc54c296aae45da71
Successfully built mecab-python
Installing collected packages: mecab-python3, mecab-python
Successfully installed mecab-python-1.0.0 mecab-python3-1.0.9
Install mecab-ko
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1381k  100 1381k    0     0  2432k      0 --:--:-- --:--:-- --:--:-- 2432k
mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes
checking for unsigned long long int... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for main in -lstdc++... yes
checking for pthread_create in -lpthread... yes
checking for pthread_join in -lpthread... yes
checking for getenv... yes
checking for opendir... yes
checking whether make is GNU Make... yes
checking if g++ supports stl <vector> (required)... yes
checking if g++ supports stl <list> (required)... yes
checking if g++ supports stl <map> (required)... yes
checking if g++ supports stl <set> (required)... yes
checking if g++ supports stl <queue> (required)... yes
checking if g++ supports stl <functional> (required)... yes

In [ ]:
import urllib.request
from konlpy.tag import Mecab
from gensim.models.word2vec import Word2Vec
import pandas as pd
import matplotlib.pyplot as plt

urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings.txt", filename="ratings.txt")

('ratings.txt', <http.client.HTTPMessage at 0x788ec83ccd00>)

In [ ]:
train_data = pd.read_table('ratings.txt')

train_data = train_data.dropna(how = 'any') # Null 값이 존재하는 행 제거
print(train_data.isnull().values.any()) # Null 값이 존재하는지 확인

# 정규 표현식을 통한 한글 외 문자 제거
train_data['document'] = train_data['document'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
train_data.head()

False

         id                                           document  label
0   8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
1   8132799  디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산...      1
2   4655635               폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.      1
3   9251303  와.. 연기가 진짜 개쩔구나.. 지루할거라고 생각했는데 몰입해서 봤다.. 그래 이런...      1
4  10067386                        안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화.      1

In [ ]:
# 불용어 정의
stopwords = ['도', '는', '다', '의', '가', '이', '은', '한', '에', '하', '고', '을', '를', '인', '듯', '과', '와', '네', '들', '듯', '지', '임', '게']

# 형태소 분석기 mecab을 사용한 토큰화 작업 (다소 시간 소요)
mecab = Mecab()
tokenized_data = []
for sentence in train_data['document']:
    temp_X = mecab.morphs(sentence) # 토큰화
    temp_X = [word for word in temp_X if not word in stopwords] # 불용어 제거
    tokenized_data.append(temp_X)

## 한국어 word2vec 훈련

In [ ]:
model = Word2Vec(
    sentences=tokenized_data, # 코퍼스
    vector_size=100, # 각 단어의 임베딩된 차원 즉 단어의 벡터 크기
    window=5, # Context Window의 크기
    min_count=5, # 단어 최소 빈도수 제한. 즉 빈도가 낮은 단어는 학습 안함
    workers=4, # 학습을 위한 프로세서(cpu)의 개수
    sg=1 # Skip Gram 사용 여부. 0이면 CBOW, 1이면 Skip Gram
)

In [ ]:
model.wv.most_similar("최민식")

[('신들린', 0.80084228515625),
 ('한석규', 0.7949563264846802),
 ('연기파', 0.7873964309692383),
 ('공리', 0.7804744243621826),
 ('조재현', 0.778698742389679),
 ('전도연', 0.7716269493103027),
 ('이요원', 0.7700812816619873),
 ('황정민', 0.7688023447990417),
 ('김명민', 0.7687551975250244),
 ('톰크루즈', 0.7681838274002075)]

In [ ]:
model.wv.most_similar("이병헌")

[('공리', 0.8117637634277344),
 ('로버트드니로', 0.7937614321708679),
 ('이요원', 0.7784050703048706),
 ('한석규', 0.7749030590057373),
 ('주윤발', 0.7726640105247498),
 ('키아누리브스', 0.7713601589202881),
 ('양동근', 0.770372748374939),
 ('박상민', 0.7703065276145935),
 ('김하늘', 0.7646604180335999),
 ('톰크루즈', 0.7625206112861633)]

In [ ]:
model.wv.most_similar("히어로")

[('sf', 0.7625506520271301),
 ('마블', 0.7549216747283936),
 ('물중', 0.7409140467643738),
 ('첩', 0.7395570278167725),
 ('슬래셔', 0.7366157174110413),
 ('판타지', 0.7205896377563477),
 ('러시아워', 0.7089784145355225),
 ('극화', 0.7087457776069641),
 ('정통', 0.7074055075645447),
 ('키드', 0.7064409255981445)]

In [ ]:
model.wv.most_similar("로맨스")

[('로맨틱', 0.7452554702758789),
 ('판타지', 0.7392570972442627),
 ('멜', 0.73531574010849),
 ('미스터리', 0.7326774001121521),
 ('코미디', 0.7303668260574341),
 ('멘스', 0.7300076484680176),
 ('로코', 0.728965699672699),
 ('멜로', 0.7258728742599487),
 ('코메디', 0.7205857038497925),
 ('스릴러', 0.7203481793403625)]

In [ ]:
model.wv.save_word2vec_format("kor_w2v")

In [ ]:
# 오타나 없는 단어(신조어)에 대해 매우 취약하다.
model.wv.most_similar("죄민식")

KeyError: "Key '죄민식' not present in vocabulary"

# FastText

In [ ]:
loaded_model.most_similar("overacting")

KeyError: "Key 'overacting' not present in vocabulary"

In [ ]:
loaded_model.most_similar("greatteee")

KeyError: "Key 'greatteee' not present in vocabulary"

In [ ]:
from gensim.models import FastText

fasttext_model = FastText(
    sentences=result,
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    sg=1
)

In [ ]:
fasttext_model.wv.most_similar("overacting")

[('subtracting', 0.8932902216911316),
 ('distracting', 0.8894063830375671),
 ('contracting', 0.8699906468391418),
 ('interacting', 0.8589096069335938),
 ('overeating', 0.853086531162262),
 ('dissecting', 0.8525210022926331),
 ('extracting', 0.8520530462265015),
 ('overarching', 0.8495829701423645),
 ('impacting', 0.8494063019752502),
 ('speculating', 0.8455122113227844)]

In [ ]:
fasttext_model.wv.most_similar("memorrrry")

[('memo', 0.8580817580223083),
 ('memoir', 0.799418568611145),
 ('nemo', 0.7942867279052734),
 ('memory', 0.7870851755142212),
 ('memorize', 0.7793874740600586),
 ('emory', 0.7585910558700562),
 ('memoirs', 0.7515826225280762),
 ('awry', 0.7306976914405823),
 ('rehearsal', 0.725237250328064),
 ('rehearse', 0.7248262166976929)]

## 한국어 FastText

In [ ]:
# 한글 자모 단위 처리 패키지 설치
!pip install hgtk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting hgtk
  Downloading hgtk-0.2.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: hgtk
Successfully installed hgtk-0.2.0

In [ ]:
# fasttext 설치
!git clone https://github.com/facebookresearch/fastText.git
%cd fastText
!make
!pip install .

Cloning into 'fastText'...
remote: Enumerating objects: 3930, done.
remote: Counting objects: 100% (964/964), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 3930 (delta 873), reused 825 (delta 825), pack-reused 2966
Receiving objects: 100% (3930/3930), 8.24 MiB | 14.65 MiB/s, done.
Resolving deltas: 100% (2505/2505), done.
/content/fastText
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/args.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/autotune.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/matrix.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/dictionary.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/loss.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/productquantizer.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/densematrix.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/quantmatrix.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/vector.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/model.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/utils.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/meter.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG -c src/fasttext.cc
c++ -pthread -std=c++11 -march=native -O3 -funroll-loops -DNDEBUG args.o autotune.o matrix.o dictionary.o loss.o productquantizer.o densematrix.o quantmatrix.o vector.o model.o utils.o meter.o fasttext.o src/main.cc -o fasttext
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing /content/fastText
  Preparing metadata (setup.py) ... done
Collecting pybind11>=2.2
  Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from fasttext==0.9.2) (67.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from fasttext==0.9.2) (1.22.4)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... done
  Created wheel for fasttext: filename=fasttext-0.9.2-cp39-cp39-linux_x86_64.whl size=4381799 sha256=3e991cbfd37476a671712ae8227b4f8929be28ee513e6922c56bcfbf1c94621d
  Stored in directory: /tmp/pip-ephem-wheel-cache-zwcr868z/wheels/2d/3b/6c/b1dab8ae56dbff3fc7c26103ce1f0646f1a39f6a06db46db46
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.2 pybind11-2.10.4

## hgtk 튜토리얼

In [ ]:
import hgtk

In [ ]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/bab2min/corpus/master/sentiment/naver_shopping.txt", filename="ratings_total.txt")

('ratings_total.txt', <http.client.HTTPMessage at 0x7f2e448b2820>)

In [ ]:
total_data = pd.read_table('ratings_total.txt', names=['ratings', 'reviews'])
print('전체 리뷰 개수 :',len(total_data)) # 전체 리뷰 개수 출력

전체 리뷰 개수 : 200000

위의 링크로부터 전체 데이터에 해당하는 ratings_total.txt를 다운로드합니다. 해당 데이터에는 열제목이 별도로 없습니다. 그래서 임의로 두 개의 열제목인 'ratings'와 'reviews'를 추가해주겠습니다.

In [ ]:
total_data[:5]

   ratings                                            reviews
0        5                                            배공빠르고 굿
1        2                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2        5  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3        2  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4        5                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ

한글의 자모를 처리하는 패키지인 hgtk를 사용하기에 앞서 간단히 사용법을 익혀봅시다. hgtk의 checker를 사용하면 입력이 한글인지 아닌지를 판단하여 True 또는 False를 리턴합니다.

In [ ]:
# 한글인지 체크
hgtk.checker.is_hangul('ㄱ')

True

In [ ]:
# 한글인지 체크
hgtk.checker.is_hangul('28')

False

hgtk의 letter를 사용하면 음절을 자모 단위로 분리하거나, 자모의 시퀀스를 다시 음절로 조합할 수 있습니다. 이는 각각 decompose와 compose로 가능합니다.

In [ ]:
# 음절을 초성, 중성, 종성으로 분해
hgtk.letter.decompose('남')

('ㄴ', 'ㅏ', 'ㅁ')

In [ ]:
# 초성, 중성을 결합
hgtk.letter.compose('ㄴ', 'ㅏ')

'나'

In [ ]:
# 초성, 중성, 종성을 결합
hgtk.letter.compose('ㄴ', 'ㅏ', 'ㅁ')

'남'

한글이 아닌 입력이 들어오거나 음절로 조합할 수 없는 경우 NotHangulException을 발생시킵니다.

In [ ]:
# 한글이 아닌 입력에 대해서는 에러 발생.
hgtk.letter.decompose('1')

NotHangulException: ignored

In [ ]:
# 결합할 수 없는 상황에서는 에러 발생
hgtk.letter.compose('ㄴ', 'ㅁ', 'ㅁ')

NotHangulException: ignored

## 데이터 전처리

위에서 사용했던 hgtk.letter.decompose()를 사용하여 특정 단어가 들어오면 이를 초성, 중성, 종성으로 나누는 함수 word_to_jamo를 구현합니다. 단, 종성이 없는 경우에는 해당 위치에 종성이 없었다는 것을 표시해주기 위해서 종성의 위치에 특수문자 '-'를 넣어주었습니다.

In [ ]:
def word_to_jamo(token):
  def to_special_token(jamo):
    if not jamo:
      return '-'
    else:
      return jamo

  decomposed_token = ''
  for char in token:
    try:
      # char(음절)을 초성, 중성, 종성으로 분리
      cho, jung, jong = hgtk.letter.decompose(char)

      # 자모가 빈 문자일 경우 특수문자 -로 대체
      cho = to_special_token(cho)
      jung = to_special_token(jung)
      jong = to_special_token(jong)
      decomposed_token = decomposed_token + cho + jung + jong

    # 만약 char(음절)이 한글이 아닐 경우 자모를 나누지 않고 추가
    except Exception as exception:
      if type(exception).__name__ == 'NotHangulException':
        decomposed_token += char

  # 단어 토큰의 자모 단위 분리 결과를 추가
  return decomposed_token

해당 함수에 임의의 단어 '남동생'을 넣어 정상적으로 분리하는지 테스트해봅시다.

In [ ]:
word_to_jamo('남동생')

'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'

'남동생'이 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'으로 분리된 것을 확인할 수 있습니다. 이번에는 임의의 단어 '여동생'을 넣어서 테스트해봅시다.

In [ ]:
word_to_jamo('여동생')

'ㅇㅕ-ㄷㅗㅇㅅㅐㅇ'

'여동생'의 경우 여에 종성이 없으므로 종성의 위치에 특수문자 '-'가 대신 들어간 것을 확인할 수 있습니다. 단순 형태소 분석을 했을 경우와 형태소 분석 후에 다시 자모 단위로 분해하는 경우를 동일한 예문을 통해 비교해봅시다. 우선 단순 형태소 분석을 했을 경우입니다.

In [ ]:
mecab = Mecab()

In [ ]:
print(mecab.morphs('선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다.'))

['선물', '용', '으로', '빨리', '받', '아서', '전달', '했어야', '하', '는', '상품', '이', '었', '는데', '머그', '컵', '만', '와서', '당황', '했', '습니다', '.']

우리가 일반적으로 봐왔던 형태소 분석 결과입니다. word_to_jamo 함수를 형태소 분석 후 호출하도록 하여 형태소 토큰들을 자모 단위로 분해하는 함수 tokenize_by_jamo를 정의합니다.

In [ ]:
def tokenize_by_jamo(s):
    return [word_to_jamo(token) for token in mecab.morphs(s)]

형태소 분석 후 자모 단위로 다시 한 번 분해한 경우입니다.

In [ ]:
print(tokenize_by_jamo('선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다.'))

['ㅅㅓㄴㅁㅜㄹ', 'ㅇㅛㅇ', 'ㅇㅡ-ㄹㅗ-', 'ㅃㅏㄹㄹㅣ-', 'ㅂㅏㄷ', 'ㅇㅏ-ㅅㅓ-', 'ㅈㅓㄴㄷㅏㄹ', 'ㅎㅐㅆㅇㅓ-ㅇㅑ-', 'ㅎㅏ-', 'ㄴㅡㄴ', 'ㅅㅏㅇㅍㅜㅁ', 'ㅇㅣ-', 'ㅇㅓㅆ', 'ㄴㅡㄴㄷㅔ-', 'ㅁㅓ-ㄱㅡ-', 'ㅋㅓㅂ', 'ㅁㅏㄴ', 'ㅇㅘ-ㅅㅓ-', 'ㄷㅏㅇㅎㅘㅇ', 'ㅎㅐㅆ', 'ㅅㅡㅂㄴㅣ-ㄷㅏ-', '.']

자모 단위 FastText에서는 위와 같이 각 형태소 분석 결과 토큰들이 추가적으로 자모 단위로 분해된 토큰들을 가지고 학습을 하게 됩니다. 전체 데이터에 대해서 위의 자모 단위 토큰화를 적용해봅시다.

In [ ]:
from tqdm import tqdm

In [ ]:
tokenized_data = []

for sample in total_data['reviews'].to_list():
    tokenzied_sample = tokenize_by_jamo(sample) # 자소 단위 토큰화
    tokenized_data.append(tokenzied_sample)

첫번째 샘플을 출력해봅시다.

In [ ]:
tokenized_data[0]

['ㅂㅐ-ㄱㅗㅇ', 'ㅃㅏ-ㄹㅡ-', 'ㄱㅗ-', 'ㄱㅜㅅ']

'배공빠르고 굿'이라는 기존 샘플이 형태소 분석 후에는 ['배공', '빠르', '고', '굿']으로 분해되었으며, 이를 다시 자모 단위로 나누면서 ['ㅂㅐ-ㄱㅗㅇ', 'ㅃㅏ-ㄹㅡ-', 'ㄱㅗ-', 'ㄱㅜㅅ']라는 결과가 됩니다. 그런데 이렇게 바꾸고나니 원래 단어가 무엇이었는지 알아보기 힘들다는 문제가 있습니다. 출력했을 때, 사용자가 기존의 단어가 무엇이었는지를 쉽게 알아보기 위해 초성, 중성, 종성을 입력받으면 역으로 단어로 바꿔주는 jamo_to_word 함수를 구현합니다.

In [ ]:
def jamo_to_word(jamo_sequence):
  tokenized_jamo = []
  index = 0

  # 1. 초기 입력
  # jamo_sequence = 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'

  while index < len(jamo_sequence):
    # 문자가 한글(정상적인 자모)이 아닐 경우
    if not hgtk.checker.is_hangul(jamo_sequence[index]):
      tokenized_jamo.append(jamo_sequence[index])
      index = index + 1

    # 문자가 정상적인 자모라면 초성, 중성, 종성을 하나의 토큰으로 간주.
    else:
      tokenized_jamo.append(jamo_sequence[index:index + 3])
      index = index + 3

  # 2. 자모 단위 토큰화 완료
  # tokenized_jamo : ['ㄴㅏㅁ', 'ㄷㅗㅇ', 'ㅅㅐㅇ']

  word = ''
  try:
    for jamo in tokenized_jamo:

      # 초성, 중성, 종성의 묶음으로 추정되는 경우
      if len(jamo) == 3:
        if jamo[2] == "-":
          # 종성이 존재하지 않는 경우
          word = word + hgtk.letter.compose(jamo[0], jamo[1])
        else:
          # 종성이 존재하는 경우
          word = word + hgtk.letter.compose(jamo[0], jamo[1], jamo[2])
      # 한글이 아닌 경우
      else:
        word = word + jamo

  # 복원 중(hgtk.letter.compose) 에러 발생 시 초기 입력 리턴.
  # 복원이 불가능한 경우 예시) 'ㄴ!ㅁㄷㅗㅇㅅㅐㅇ'
  except Exception as exception:
    if type(exception).__name__ == 'NotHangulException':
      return jamo_sequence

  # 3. 단어로 복원 완료
  # word : '남동생'

  return word

해당 함수의 내부 동작 방식을 설명하기 위해 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'이라는 임의의 입력이 들어왔을 때를 가정해봅시다. 초기 입력이 들어왔을 때는 jamo_sequence라는 변수에 저장되어져 있습니다. while 문 내부에서는 jamo_sequences의 각 문자에 대해서 세 개씩 분리하여 초성, 중성, 종성을 하나의 묶음으로 간주합니다. while문을 지나고나면 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'이라는 문자열은 ['ㄴㅏㅁ', 'ㄷㅗㅇ', 'ㅅㅐㅇ']이라는 리스트로 변환이 되며, 해당 리스트는 tokenized_jamo라는 변수에 저장되어져 있습니다. 그리고 각 리스트의 원소를 hgtk.letter.compose()의 입력으로 넣어 기존의 음절로 복원합니다. 결과적으로 '남동생'이라는 단어로 복원되고 해당 함수는 '남동생'을 최종 결과로서 리턴합니다.

실제로 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'을 입력으로 넣어 결과를 확인해봅시다.

In [ ]:
jamo_to_word('ㄴㅏㅁㄷㅗㅇㅅㅐㅇ')

'남동생'

## FastText

자모 단위로 토큰화 된 데이터를 가지고 FastText를 학습시켜봅시다.

In [ ]:
import fasttext

FastText 학습을 위해서 기존 훈련 데이터를 txt 파일 형식으로 저장해야합니다.

In [ ]:
with open('tokenized_data.txt', 'w') as out:
  for line in tqdm(tokenized_data, unit=' line'):
    out.write(' '.join(line) + '\n')

100%|██████████| 200000/200000 [00:00<00:00, 473187.85 line/s]

두 가지 모델 Skip-gram과 CBoW 중 CBoW를 선택했습니다.

In [ ]:
model = fasttext.train_unsupervised('tokenized_data.txt', model='cbow')

In [ ]:
model.save_model("fasttext.bin")

In [ ]:
model = fasttext.load_model("fasttext.bin")

학습이 완료되었습니다. 임의로 '남동생'이라는 단어의 벡터값을 확인해봅시다. 주의할 점은 학습 시 자모 단위로 분해하였기 때문에 모델에서 벡터값을 확인할 때도 자모 단위로 분해 후에 입력으로 사용해야 합니다.

In [ ]:
model[word_to_jamo('남동생')] # 'ㄴㅏㅁㄷㅗㅇㅅㅐㅇ'

array([-0.75121707, -0.09777343, -0.06479282,  0.3878322 , -0.3629536 ,
        0.444919  ,  0.17368399, -0.6492414 , -0.1460425 , -0.6556199 ,
        0.47561774,  0.15500426, -0.07597088,  0.6838326 , -0.12038054,
       -0.05893848,  0.80528766,  0.41876066,  0.5232016 , -0.76272345,
       -0.38435844, -0.48213163,  0.47253323,  0.42145985, -0.40317082,
        0.1875647 ,  0.40562132,  0.0864673 ,  0.4318442 ,  0.41785347,
        0.99820423, -1.1779842 ,  0.02945196,  0.33049268,  1.0954536 ,
        0.03768162,  0.44268563, -1.095168  , -0.23283842,  0.5355596 ,
        0.6794727 ,  0.47900698, -0.60658246,  1.2562438 , -0.24471879,
        0.46079734, -0.01676963, -0.17489414, -0.43604985,  0.34543806,
       -0.15913598,  0.2918002 ,  0.8731358 ,  1.0437014 , -0.6025581 ,
        0.2981697 ,  0.53655666, -0.05084229,  0.05335928,  0.2421371 ,
        0.17908356, -0.6660127 ,  0.934657  ,  0.09646372, -0.6387341 ,
       -0.25673625, -0.77488786, -0.07015391, -0.37226695, -0.55947345,
        0.83869666, -0.55160785, -0.6442831 , -1.1367108 , -0.5339727 ,
       -0.3735716 ,  0.1700377 , -0.10630285,  0.25655746,  0.44570395,
        0.307642  ,  0.4534266 ,  0.64409655,  0.24118307,  1.3139023 ,
       -0.68417984, -0.21984173, -0.48198634, -0.37201494, -0.602568  ,
        0.48429957,  0.07606182,  1.0860566 , -0.4922452 , -0.7560751 ,
        0.3855273 ,  0.40110067,  0.5036619 , -0.8770224 ,  0.2942066 ],
      dtype=float32)

남동생 '벡터'와 가장 유사도가 높은 벡터들을 뽑아봅시다. 이는 get_nearest_neighbors()를 사용하여 가능합니다. 두번째 인자인 k값으로 10을 주면, 가장 유사한 벡터 상위 10개를 출력합니다.

In [ ]:
model.get_nearest_neighbors(word_to_jamo('남동생'), k=10)

[(0.8809508681297302, 'ㄷㅗㅇㅅㅐㅇ'),
 (0.8286653161048889, 'ㄴㅏㅁㅊㅣㄴ'),
 (0.7495564818382263, 'ㄴㅏㅁㅍㅕㄴ'),
 (0.7464686036109924, 'ㅅㅐㅇㅇㅣㄹ'),
 (0.735321581363678, 'ㅊㅣㄴㄱㅜ-'),
 (0.7235512733459473, 'ㄴㅏㅁㅇㅏ-'),
 (0.7162966132164001, 'ㅈㅗ-ㅋㅏ-'),
 (0.7039785385131836, 'ㄴㅏㄴㅅㅐㅇ'),
 (0.6938914656639099, 'ㄴㅏㅁㅁㅐ-'),
 (0.6907734870910645, 'ㅇㅓㄴㄴㅣ-')]

그런데 출력으로 나오는 벡터들도 자모 단위로 분해해서 나오기 때문에 읽기가 어렵습니다. 이전에 만들어준 jamo_to_word 함수를 사용하여 출력 결과를 좀 더 깔끔하게 확인할 수 있습니다.

In [ ]:
def transform(word_sequence):
  return [(jamo_to_word(word), similarity) for (similarity, word) in word_sequence]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('남동생'), k=10)))

[('동생', 0.8809508681297302), ('남친', 0.8286653161048889), ('남편', 0.7495564818382263), ('생일', 0.7464686036109924), ('친구', 0.735321581363678), ('남아', 0.7235512733459473), ('조카', 0.7162966132164001), ('난생', 0.7039785385131836), ('남매', 0.6938914656639099), ('언니', 0.6907734870910645)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('남동쉥'), k=10)))

[('남동생', 0.903592586517334), ('남친', 0.8046611547470093), ('남매', 0.7930417656898499), ('남짓', 0.762987494468689), ('남김', 0.7530947327613831), ('남긴', 0.7364609241485596), ('남여', 0.7232005000114441), ('남아', 0.7184900045394897), ('남겼', 0.7151230573654175), ('남녀', 0.7114916443824768)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('남동셍ㅋ'), k=10)))

[('남동생', 0.8321648240089417), ('남친', 0.7351190447807312), ('남김', 0.7152878642082214), ('남짓', 0.6808348298072815), ('남매', 0.6775488257408142), ('남길', 0.6609652638435364), ('남긴', 0.6552697420120239), ('남녀', 0.647351861000061), ('남여', 0.6399891972541809), ('남겼', 0.6360887885093689)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('난동생'), k=10)))

[('남동생', 0.8605595231056213), ('난생', 0.8415924906730652), ('동생', 0.790320098400116), ('남편', 0.7590644359588623), ('남아', 0.7492496967315674), ('남친', 0.7343378067016602), ('중학생', 0.7026507258415222), ('남매', 0.6978760957717896), ('학생', 0.6911318898200989), ('반신욕', 0.6841548681259155)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('낫동생'), k=10)))

[('남동생', 0.9290178418159485), ('동생', 0.88860684633255), ('남편', 0.7612314820289612), ('난생', 0.7438672184944153), ('남친', 0.7399165630340576), ('조카', 0.7122743725776672), ('중학생', 0.7097246646881104), ('친구', 0.7055485248565674), ('남아', 0.7020242810249329), ('학생', 0.6935662031173706)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('납동생'), k=10)))

[('남동생', 0.9063751101493835), ('동생', 0.8477023243904114), ('난생', 0.77754145860672), ('남편', 0.7669044733047485), ('남친', 0.7531878352165222), ('남아', 0.7262435555458069), ('중학생', 0.7041069269180298), ('조카', 0.697344958782196), ('나눴', 0.6933421492576599), ('고등학생', 0.6913762092590332)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('냚동생'), k=10)))

[('동생', 0.9683497548103333), ('남동생', 0.8915597796440125), ('조카', 0.781344473361969), ('친구', 0.7688440680503845), ('생일', 0.7618958353996277), ('언니', 0.7535653114318848), ('학생', 0.7456444501876831), ('중학생', 0.7425476312637329), ('어린이집', 0.7221997380256653), ('초등학생', 0.7162642478942871)]

In [ ]:
print(transform(model.get_nearest_neighbors(word_to_jamo('제품^^'), k=10)))

[('제품', 0.9403702616691589), ('제풍', 0.8477377891540527), ('반제품', 0.7876006960868835), ('완제품', 0.7851003408432007), ('상품', 0.7712583541870117), ('최상품', 0.7655972838401794), ('타제품', 0.7592073082923889), ('재품', 0.7041335105895996), ('화학제품', 0.6883261799812317), ('상품명', 0.6684249043464661)]